waste_classes:
  plastic_bottle: "Recycle Waste"
  can: "Recycle Waste"
  paper: "Recycle Waste"

  plastic_bag: "General Waste"
  instant_noodle: "General Waste"
  mask: "General Waste"

  banana: "Organic Waste"
  apple: "Organic Waste"
  orange: "Organic Waste"

  battery: "Hazardous Waste"

special_classes:
  shutdown_card: "shutdown"